baseURL = "https://thehdaze.com/"
locale = "en-US"
title = "HDaze"
theme = "hugo-theme-monochrome"

pluralizeListTitles = false
summaryLength = 20
enableEmoji = true

[pagination]
  pagerSize = 10

[params]
  navbar_title = "HDaze"
  footer = "Copyright © 2026 HDaze"
  color_scheme = "light" # "light" or "dark"
  imageBaseURL = "https://cdn.thehdaze.com/theHDaze/static/images/"
  enable_toc = true
  toc_position = "right"
  enable_collapsible_toc = false
  enable_collapsible_changelogs = false

  hide_navbar_on_scroll = true
  navbar_width = "wide" # "normal" | "wide" | "extra-wide"

  enable_header_anchor = true
  enable_zooming_js = true
  enable_math = false

  enable_site_search = true
  enable_open_graph = true
  enable_twitter_cards = true

  [params.author]
    name = "HDaze"

  [params.list_layout]
    enable_group_by_year = true
    enable_show_date = true
    enable_pagination = true

  [params.syntax_highlight]
    lib = "builtin" # "builtin" | "prism.js"

    [params.syntax_highlight.builtin]
      enable_code_copy = true

[[menu.navbar]]
  identifier = "nav-blog"
  name = "博客 | Blog"
  url = "/blog/"
  weight = 10

[[menu.navbar]]
  identifier = "nav-poems"
  name = "黑雨 | Poems"
  url = "/诗/"
  weight = 20

[[menu.navbar]]
  identifier = "nav-about"
  name = "关于 | About"
  url = "/about/"
  weight = 30

[[menu.navbar]]
  identifier = "nav-tags"
  name = "标签 | Tags"
  url = "/tags/"
  weight = 40

[[menu.navbar]]
  identifier = "nav-rss"
  name = "RSS"
  url = "/index.xml"
  weight = 50
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "series"
    weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

  [services]
  [services.rss]
    limit = 20

[params.socials]
  mastodon = "https://m.cmx.im/@HDaze"
 # rss = "/index.xml"
  # github = "https://github.com/yourname"
  # email = "mailto:you@example.com"