baseURL = 'https://hdaze.github.io/'
languageCode = 'en-us'
title = 'HDaze'
theme = 'hugo-book'



[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

  BookLogo = 'HDaze.png'

 BookSection = '*'
  
 