baseURL = 'https://hdaze.github.io/'
languageCode = 'en-us'
title = 'HDaze'
theme = 'hugo-book'



[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

  BookLogo = 'HDaze.png'

 BookSection = '*'

front_page_content = ["blog", "诗"]
 menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "blog", URL = "/blog/", Pre = "Recent", HasChildren = true, Limit = 5},
        {Name = "诗", URL = "/诗/", Pre = "Recent", HasChildren = true, Limit = 5},
    ]
      rss_icon = true

[taxonomies]
    series = 'series'
    tags = 'tags'