baseURL = 'https://thehdaze.com/'
languageCode = 'en-us'
title = 'HDaze'
theme = 'poison'
paginate = 10
pluralizelisttitles = false

[params]
    brand = "HDaze"                      # name of your site - appears in the sidebar
    # remote_brand_image = 'https://github.com/USERNAME.png' # path to a remote file
    brand_image = "/logo1.png"    # path to the image shown in the sidebar
    # description = "Find Connections" # Used as default meta description if not specified in front matter
    dark_mode = false                      # optional - defaults to false
    favicon = "/favicon2.png"         # path to favicon (defaults to favicon.png)

    front_page_content = ["blog", "诗"] # Equivalent to the default value, add page bundle names to include them on the front page.
    imageBaseURL = "https://cdn.thehdaze.com/theHDaze/static/images/"
  
  menu = [
    {Name = "博客 | Blog", URL = "/blog/", HasChildren = false},
    {Name = "黑雨 | Poems", URL = "/诗/", HasChildren = false},
    {Name = "关于 | About", URL = "/about/", HasChildren = false},
  ]
 
  rss_icon = true
  rss_section = "blog"
      
  mastodon_url = "https://m.cmx.im/@HDaze"
   
  sidebar_socials_color = "#f26522"   
  

    # NOTE: If using Remark42 as commenting engine, uncomment and configure these lines
    # remark42 = true
    # remark42_host = "https://yourhost.com"
    # remark42_site_id = "your_site_id"

    # NOTE: The following three params are optional and are used to create meta tags + enhance SEO.
    # og_image = ""                       # path to social icon - front matter: image takes precedent, then og_image, then brand_url
                                          # this is also used in the schema output as well. Image is resized to max 1200x630
                                          # For this to work though og_image and brand_url must be a path inside the assets directory
                                          # e.g. /assets/images/site/og-image.png becomes images/site/og-image.png
    # publisher_icon = ""                 # path to publisher icon - defaults to favicon, used in schema
 
  summaryLength = 20  # Adjust the number of words to fit your needs
enableEmoji = true

[params.meta]
    favicon = true

[taxonomies]
    series = 'series'
    tags = 'tags'


[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "series"
    weight = 50

[outputs]
section = ["HTML"]
home = ["HTML", 'rss']



